apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-robot
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["bind"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["create","watch","list","get"]    
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["create","watch","list","get","update"]   
- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumeclaims"]
  verbs: ["create","watch","list","get"]      
- apiGroups: ["","apps","batch","extensions","policy","rbac.authorization.k8s.io"]
  resources: ["namespaces"]
  verbs: ["create","update","delete","watch","list","get"]      
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create","delete","watch","list","get"]  
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch","list","get"] 
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["watch","list","get"]   
